"""
Pydantic model representing the response returned by the ChatOps Assistant.
"""

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    Structured response generated by the ChatOps Assistant.
    """

    answer: str = Field(
        description="Answer to the user's question."
    )

