"""
Runbook Generator

Generates a production runbook from an incident description
using the configured Large Language Model (LLM).
"""

from runbook_generator.src.prompts.runbook_prompt import RUNBOOK_PROMPT
from core.llm_client import LLMClient
from core.logger import get_logger

# Create a logger for this module.
logger = get_logger("runbook_generator")


class RunbookGenerator:
    """
    Generates production runbooks using an LLM.
    """

    def __init__(self):
        # Create a reusable LLM client.
        self.llm_client = LLMClient()

    def generate(self, incident: str) -> str:
        """
        Generate a production runbook from an incident description.

        Args:
            incident: Raw incident details.

        Returns:
            A Markdown runbook generated by the LLM.
        """

        # Log the start of the runbook generation process.
        logger.info("Starting runbook generation.")

        # Build the prompt using the incident details.
        prompt = RUNBOOK_PROMPT.format(
            incident=incident
        )

        # Log before sending the request to the LLM.
        logger.info("Sending runbook request to LLM.")

        # Generate the runbook.
        runbook = self.llm_client.generate(prompt)

        # Log successful completion.
        logger.info("Runbook generated successfully.")

        # Return the generated runbook.
        return runbook